# Form implementation generated from reading ui file 'c:\Users\owner\Documents\桌面文件\记带功\Task-Management-Assistant\Task-Management-Assistant\cal4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1680, 1050)
        Dialog.setStyleSheet("color: rgb(70, 255, 153);\n"
"background-color: rgb(85, 170, 255);")
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(70, 50, 1001, 381))
        self.scrollArea.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"border-width: 12px;\n"
"border-style: solid;\n"
"border-radius: 40px;\n"
"border-color: rgb(173, 221, 231);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(88, 182, 255);\n"
"    width: 16px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"/* Handle Bar Vertical*/\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(98, 161, 232);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(173, 244, 179);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(128, 217, 129);\n"
"}\n"
"/*button top scrollbar*/\n"
"QScrollBar::sub-line:vertical{\n"
"    border: none;\n"
"    background-color:  rgb(110, 248, 243);\n"
"    height: 15;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"\n"
"/*button bottom  scrollbar*/\n"
"QScrollBar::add-line:vertical{\n"
"    border: none;\n"
"    background-color:  rgb(110, 248, 243);\n"
"    height: 15;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*Reset Arrow*/\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background-color: rgb(225, 215, 222);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(0, 239, 115);\n"
"    margin: 0px 15 0px 15;\n"
"    hieght: 14px;\n"
"}\n"
"/* Handle Bar Horizontal*/\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(0, 189, 95);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*button top scrollbar*/\n"
"QScrollBar::sub-line:horizontal{\n"
"    border: none;\n"
"    background-color:  rgb(0, 239, 115);\n"
"    width: 15;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*button bottom  scrollbar*/\n"
"QScrollBar::add-line:horizontal{\n"
"    border: none;\n"
"    background-color:  rgb(0, 239, 115);\n"
"    width: 15;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*Reset Arrow*/\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background-color: rgb(0, 207, 152);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 977, 357))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(580, 590, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(830, 590, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(730, 590, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("* {\n"
"    background-color: rgb(173, 221, 231);\n"
"color: rgb(0, 170, 127);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(1090, 20, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("* {\n"
"    background-color: rgb(173, 221, 231);\n"
"color: rgb(170, 85, 255);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.button = QtWidgets.QPushButton(parent=Dialog)
        self.button.setGeometry(QtCore.QRect(90, 840, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Charter")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button.setFont(font)
        self.button.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.button.setObjectName("button")
        self.addPlan = QtWidgets.QPushButton(parent=Dialog)
        self.addPlan.setGeometry(QtCore.QRect(740, 850, 351, 101))
        font = QtGui.QFont()
        font.setFamily("Charter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.addPlan.setFont(font)
        self.addPlan.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.addPlan.setObjectName("addPlan")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 480, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(550, 710, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("* {\n"
"    background-color: rgb(173, 221, 231);\n"
"color: rgb(0, 170, 127);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(1190, 710, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("* {\n"
"    background-color: rgb(173, 221, 231);\n"
"color: rgb(0, 170, 127);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(1040, 710, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(1290, 710, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(1250, 20, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("* {\n"
"    background-color: rgb(173, 221, 231);\n"
"color: rgb(170, 85, 255);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.prepareButton = QtWidgets.QPushButton(parent=Dialog)
        self.prepareButton.setGeometry(QtCore.QRect(1370, 840, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Charter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.prepareButton.setFont(font)
        self.prepareButton.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.prepareButton.setObjectName("prepareButton")
        self.planList = QtWidgets.QScrollArea(parent=Dialog)
        self.planList.setGeometry(QtCore.QRect(1110, 150, 521, 381))
        self.planList.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"border-width: 12px;\n"
"border-style: solid;\n"
"border-radius: 40px;\n"
"border-color: rgb(173, 221, 231);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(88, 182, 255);\n"
"    width: 16px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 8px;\n"
"}\n"
"/* Handle Bar Vertical*/\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(98, 161, 232);\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(173, 244, 179);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(128, 217, 129);\n"
"}\n"
"/*button top scrollbar*/\n"
"QScrollBar::sub-line:vertical{\n"
"    border: none;\n"
"    background-color:  rgb(110, 248, 243);\n"
"    height: 15;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"\n"
"/*button bottom  scrollbar*/\n"
"QScrollBar::add-line:vertical{\n"
"    border: none;\n"
"    background-color:  rgb(110, 248, 243);\n"
"    height: 15;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*Reset Arrow*/\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background-color: rgb(225, 215, 222);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(0, 239, 115);\n"
"    margin: 0px 15 0px 15;\n"
"    hieght: 14px;\n"
"}\n"
"/* Handle Bar Horizontal*/\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(0, 189, 95);\n"
"    min-width: 30px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*button top scrollbar*/\n"
"QScrollBar::sub-line:horizontal{\n"
"    border: none;\n"
"    background-color:  rgb(0, 239, 115);\n"
"    width: 15;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*button bottom  scrollbar*/\n"
"QScrollBar::add-line:horizontal{\n"
"    border: none;\n"
"    background-color:  rgb(0, 239, 115);\n"
"    width: 15;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"    background-color: rgb(0, 161, 118);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"    background-color: rgb(0, 140, 103);\n"
"}\n"
"/*Reset Arrow*/\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background-color: rgb(0, 207, 152);\n"
"}")
        self.planList.setWidgetResizable(True)
        self.planList.setObjectName("planList")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 497, 357))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.planList.setWidget(self.scrollAreaWidgetContents_2)
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(1290, 100, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("* {\n"
"    background-color: rgb(173, 221, 231);\n"
"color: rgb(170, 85, 255);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 15px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.deleteButton = QtWidgets.QPushButton(parent=Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(1200, 540, 351, 101))
        font = QtGui.QFont()
        font.setFamily("Charter")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("* {background-color: rgb(173, 221, 231);\n"
"color: rgb(34, 137, 146);\n"
"border-width: 9px;\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"border-color: rgb(173, 221, 231);\n"
"font: bold;\n"
"}\n"
"")
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", ":"))
        self.label_4.setText(_translate("Dialog", "# of Tasks:"))
        self.button.setText(_translate("Dialog", "Back to Main Page"))
        self.addPlan.setText(_translate("Dialog", "Add to the Plan!"))
        self.comboBox.setItemText(0, _translate("Dialog", "Select Type"))
        self.comboBox.setItemText(1, _translate("Dialog", "Daily Task"))
        self.comboBox.setItemText(2, _translate("Dialog", "One-Time Task"))
        self.comboBox.setItemText(3, _translate("Dialog", "Scheduled Task"))
        self.label_5.setText(_translate("Dialog", "TO"))
        self.label_6.setText(_translate("Dialog", ":"))
        self.label_7.setText(_translate("Dialog", "0"))
        self.prepareButton.setText(_translate("Dialog", "Next"))
        self.label_8.setText(_translate("Dialog", "Plan List"))
        self.deleteButton.setText(_translate("Dialog", "Delete Plans"))
