# Form implementation generated from reading ui file 'c:\Users\owner\Documents\桌面文件\记带功\Task-Management-Assistant-1\cal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2100, 1260)
        MainWindow.setMinimumSize(QtCore.QSize(2100, 1260))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(0, 251, 255), stop:1 rgb(0, 160, 200));\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(0, 70, 1011, 731))
        self.calendar.setAutoFillBackground(False)
        self.calendar.setStyleSheet("background-color: rgb(91, 207, 255);\n"
"alternate-background-color: rgb(0, 255, 204);\n"
"selection-background-color: rgb(171, 255, 92);\n"
"selection-color: rgb(45, 45, 45);")
        self.calendar.setObjectName("calendar")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 95, 1011, 30))
        self.label.setStyleSheet("background-color: rgb(167, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1020, 0, 171, 61))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(61, 255, 79), stop:1 rgb(156, 255, 12))")
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1210, -10, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1120, 100, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(100, 122, 255);")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(1120, 150, 521, 661))
        self.scrollArea.setStyleSheet("/*Background Color*/\n"
"* {background-color: rgb(85, 170, 127);}\n"
"/*Vertical Scrollbar*/\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(116, 170, 0);\n"
"    width: 16px;\n"
"    border radius: 0px;\n"
"}\n"
"/* Handle Bar Vertical*/\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(116, 170, 0);\n"
"    min-height: 30px;\n"
"    border radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -92, 718, 818))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_2.setMinimumSize(QtCore.QSize(700, 800))
        self.frame_2.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2100, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Date!"))
        self.pushButton.setText(_translate("MainWindow", "To Screen2"))
        self.label_2.setText(_translate("MainWindow", "Plans"))
